version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: hospitaldb
      POSTGRES_USER: hospitaluser
      POSTGRES_PASSWORD: hospitalpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
