services:
  - type: web
    name: hospital-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hospital_api.wsgi:application
    envVars:
      - key: DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "hospital-api.onrender.com"
      - key: SECRET_KEY
        generateValue: true